# Generated by Django 5.0.6 on 2024-07-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='data_entrega',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='data_prazo',
            field=models.DateField(),
        ),
    ]
